py_library(
    name = "card_testcase",
    srcs = ["card_testcase.py"],
    deps = [
        "@io_bazel_rules_webtesting//testing/web",
        "@rules_python//python/runfiles",
    ],
    visibility = ["//visibility:public"],
    testonly = True,
)
